version: '3.8'

services:
  neo4j:
    image: neo4j:5.9.0
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo:/conf
      - neo:/data
      - neo:/import
      - neo:/logs
      - neo:/plugins

volumes:
  neo:
    driver: local
