version: '3.8'

services:
  db:
    container_name: postgres-dev
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - "5432:5432"
    volumes: 
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
