version: '3.8'

services:
  db:
    container_name: mongo-dev
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

volumes:
  mongo:
    driver: local
