version: '3.8'

services:
  cache:
    image: redis:7n-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 123
    volumes: 
      - redis:/data

volumes:
  redis:
    driver: local